name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate serial number
      id: serial
      run: echo "::set-output name=number::$(date +%Y%m%d%H%M%S)"

    - name: Build Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ${{ secrets.DOCKER_IMAGE_TAG }}:${{ steps.serial.outputs.number }}

    - name: Run tests
      run: |
        pip install -r requirements.txt
        python -m unittest discover -s tests

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_IMAGE_TAG }}:${{ steps.serial.outputs.number }}