name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_IMAGE_TAG }}

    - name: Get the short commit ID
      id: vars
      run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

    - name: Deploy to AWS CodeDeploy
      uses: aws-actions/aws-code-deploy-action@v1.0.0
      with:
        application-name: ${{ secrets.CODEDEPLOY_APP_NAME }}
        deployment-group-name: ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }}
        deployment-config-name: CodeDeployDefault.OneAtATime
        description: "Deploy Docker image to EC2"
        revision-location: |
            revisionType: GitHub
            gitHubLocation:
                repository: nx1x/final-python
                commitId: ${{ steps.vars.outputs.short_sha }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
