name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_IMAGE_TAG }}

    - name: Get the short commit ID
      id: vars
      run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS CodeDeploy
      uses: aws-actions/aws-codedeploy-action@v3
      with:
        application-name: ${{ secrets.CODEDEPLOY_APP_NAME }}
        deployment-group-name: ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }}
        deployment-config-name: CodeDeployDefault.OneAtATime
        description: "Deploy Docker image to EC2"
        revision-location: |
          revisionType: GitHub
          gitHubLocation:
            repository: nx1x/final-python
            commitId: ${{ steps.vars.outputs.short_sha }}